CC = gcc
CFLAGS = -Wall

OBJ = use_linked_list.o linked_list.o

all: linked_list

linked_list: $(OBJ)
	$(CC) $(CFLAGS) -o $(OBJ)
	
use_linked_list.o : use_linked_list.c linked_list.h

linked_list.o : linked_list.c linked_list.h
	
compileonly: $(OBJ)

deleteofiles:
	del -f *.o
	
deleteexec:
	del -f linked_list.exe	

deleteall: deleteexec deleteofiles

